# Generated by Django 6.0.2 on 2026-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_checkin_habit_delete_post_checkin_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#9be9a8', max_length=24),
        ),
    ]
