# Generated by Django 6.0.2 on 2026-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='habit',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
