# Generated by Django 6.0.2 on 2026-03-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
