# Generated by Django 6.0.2 on 2026-03-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_userstats_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='country',
        ),
    ]
