# Generated by Django 6.0.2 on 2026-03-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_userstats_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
