# Generated by Django 6.0.2 on 2026-03-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='wallet_address',
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('date', models.DateField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='habits.habit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'habit', 'date'), name='uniq_xp_event')],
            },
        ),
    ]
